baseURL = "http://andrew.cobaugh.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Andrew Cobaugh"
theme = "dimension.local"
enableRobotsTXT = true
disableKinds=["RSS"]

googleAnalytics = "UA-112422997-1"

# for publishing to github pages
publishDir = "public"

[params]
	description = "IT Systems Engineer @ <a href=\"http://www.psu.edu\">Penn State</a>"
	copyright = "2017-2019"

[[params.social]]
	medium = "Github"
	icon = "github"
	link = "https://github.com/acobaugh"

[[params.social]]
	medium = "Linkedin"
	icon = "linkedin"
	link = "https://www.linkedin.com/in/andrew-cobaugh"

[[params.social]]
	medium = "Keybase"
	icon = "key"
	link = "https://keybase.io/andrewcobaugh"

[[params.social]]
	medium = "Email"
	icon = "envelope-o"
	link = "mailto:andrew.cobaugh@gmail.com"
